name: Latest blog post workflow
on:
  schedule:
    # Runs every hour
    - cron: '0 * * * *'

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://dev.to/feed/alfredoperez,https://medium.com/feed/@alfredo.perez.q,https://alfredo-perez.dev/feed.xml"
          max_post_count: 20
          feed_names: "Dev.to,Medium,Digital Garden"
